// Catalogo Deus Medical — generato dal listino ufficiale.
// price_cents = RETAIL (vendita), cost_cents = DROP SHIPPING (acquisto).
// Usato dall'import del catalogo nell'admin. NON modificare a mano:
// rigenerare dallo script se cambia il listino.

export interface DeusCategory {
  slug: string;
  name: string;
  description: string;
  position: number;
}

export interface DeusProduct {
  slug: string;
  title: string;
  shortDescription: string;
  description: string;
  category: string;
  priceCents: number;
  costCents: number;
  stock: number;
  active: boolean;
  specs: { activeName: string; packaging: string };
}

export const DEUS_CATEGORIES: DeusCategory[] = [
  { slug: "iniettabili", name: "Iniettabili", description: "Soluzioni sterili in fiale per uso intramuscolare.", position: 1 },
  { slug: "orali", name: "Orali", description: "Compresse in blister per uso orale.", position: 2 },
  { slug: "post-cycle", name: "Post Cycle (PCT)", description: "SERM, inibitori dell'aromatasi e supporto ormonale.", position: 3 },
  { slug: "brucia-grassi", name: "Brucia grassi", description: "Termogenici, ormoni tiroidei e agonisti GLP-1.", position: 4 },
  { slug: "sex-support", name: "Sex Support", description: "Supporto per la funzione sessuale.", position: 5 },
  { slug: "hgh-peptidi", name: "HGH & Peptidi", description: "Ormone della crescita e peptidi.", position: 6 },
  { slug: "sarms", name: "SARMs", description: "Modulatori selettivi del recettore degli androgeni.", position: 7 },
  { slug: "salute", name: "Salute", description: "Supporto cardiovascolare, colesterolo e accessori.", position: 8 },
];

export const DEUS_PRODUCTS: DeusProduct[] = [
  {
    slug: "3-trenbomed-150",
    title: "3-TRENBOMED 150",
    shortDescription: "Trenbolone Hexahydrobenzylcarbonate / Enanthate / Acetate 50mg/ml",
    description: "Trenbolone Hexahydrobenzylcarbonate / Enanthate / Acetate 50mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 5700,
    costCents: 3500,
    stock: 100,
    active: true,
    specs: { activeName: "Trenbolone Hexahydrobenzylcarbonate / Enanthate / Acetate 50mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "decamed-250",
    title: "DECAMED 250",
    shortDescription: "Nandrolone Decanoate 250mg/ml",
    description: "Nandrolone Decanoate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 4500,
    costCents: 2200,
    stock: 100,
    active: true,
    specs: { activeName: "Nandrolone Decanoate 250mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "decamed-pp-100",
    title: "DECAMED PP 100",
    shortDescription: "Nandrolone Phenylpropionate 100mg/ml",
    description: "Nandrolone Phenylpropionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 3400,
    costCents: 1800,
    stock: 100,
    active: true,
    specs: { activeName: "Nandrolone Phenylpropionate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "dhb-med-100",
    title: "DHB-MED 100",
    shortDescription: "Dihydroboldenone Cypionate 100mg/ml",
    description: "Dihydroboldenone Cypionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 5500,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "Dihydroboldenone Cypionate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "dianamed-100",
    title: "DIANAMED 100",
    shortDescription: "Methandienone 100mg/ml",
    description: "Methandienone 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 4000,
    costCents: 1700,
    stock: 100,
    active: true,
    specs: { activeName: "Methandienone 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "equimed-250",
    title: "EQUIMED 250",
    shortDescription: "Boldenone Undecylenate 250mg/ml",
    description: "Boldenone Undecylenate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 4200,
    costCents: 2000,
    stock: 100,
    active: true,
    specs: { activeName: "Boldenone Undecylenate 250mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "mastermed-e-200",
    title: "MASTERMED E 200",
    shortDescription: "Drostanolone Enanthate 200mg/ml",
    description: "Drostanolone Enanthate 200mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 5500,
    costCents: 3500,
    stock: 100,
    active: true,
    specs: { activeName: "Drostanolone Enanthate 200mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "mastermed-p-100",
    title: "MASTERMED P 100",
    shortDescription: "Drostanolone Propionate 100mg/ml",
    description: "Drostanolone Propionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 4400,
    costCents: 2300,
    stock: 100,
    active: true,
    specs: { activeName: "Drostanolone Propionate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "paramed-76-5",
    title: "PARAMED 76.5",
    shortDescription: "Trenbolone Hexahydrobenzylcarbonate 76.5mg/ml",
    description: "Trenbolone Hexahydrobenzylcarbonate 76.5mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 5500,
    costCents: 3900,
    stock: 100,
    active: true,
    specs: { activeName: "Trenbolone Hexahydrobenzylcarbonate 76.5mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "primomed-100",
    title: "PRIMOMED 100",
    shortDescription: "Methenolone Enanthate 100mg/ml",
    description: "Methenolone Enanthate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 7000,
    costCents: 4700,
    stock: 100,
    active: true,
    specs: { activeName: "Methenolone Enanthate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "sustamed-250",
    title: "SUSTAMED 250",
    shortDescription: "Testosterone Phenylpropionate/Decanoate/Isocaproate/Propionate 250mg/ml",
    description: "Testosterone Phenylpropionate/Decanoate/Isocaproate/Propionate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 3700,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "Testosterone Phenylpropionate/Decanoate/Isocaproate/Propionate 250mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "testomed-100",
    title: "TESTOMED 100",
    shortDescription: "Testosterone Base 100mg/ml",
    description: "Testosterone Base 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 3100,
    costCents: 1400,
    stock: 100,
    active: true,
    specs: { activeName: "Testosterone Base 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "testomed-c-250",
    title: "TESTOMED C 250",
    shortDescription: "Testosterone Cypionate 250mg/ml",
    description: "Testosterone Cypionate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 3500,
    costCents: 1700,
    stock: 100,
    active: true,
    specs: { activeName: "Testosterone Cypionate 250mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "testomed-e-250",
    title: "TESTOMED E 250",
    shortDescription: "Testosterone Enanthate 250mg/ml",
    description: "Testosterone Enanthate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 3500,
    costCents: 1700,
    stock: 100,
    active: true,
    specs: { activeName: "Testosterone Enanthate 250mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "testomed-p-100",
    title: "TESTOMED P 100",
    shortDescription: "Testosterone Propionate 100mg/ml",
    description: "Testosterone Propionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 2900,
    costCents: 1300,
    stock: 100,
    active: true,
    specs: { activeName: "Testosterone Propionate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "testomed-pp-100",
    title: "TESTOMED PP 100",
    shortDescription: "Testosterone Phenylpropionate 100mg/ml",
    description: "Testosterone Phenylpropionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 2900,
    costCents: 1300,
    stock: 100,
    active: true,
    specs: { activeName: "Testosterone Phenylpropionate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "testomed-u-250",
    title: "TESTOMED U 250",
    shortDescription: "Testosterone Undecanoate 250mg/ml",
    description: "Testosterone Undecanoate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 3300,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Testosterone Undecanoate 250mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "trenbomed-a-100",
    title: "TRENBOMED A 100",
    shortDescription: "Trenbolone Acetate 100mg/ml",
    description: "Trenbolone Acetate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 4900,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "Trenbolone Acetate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "trenbomed-e-200",
    title: "TRENBOMED E 200",
    shortDescription: "Trenbolone Enanthate 200mg/ml",
    description: "Trenbolone Enanthate 200mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 5500,
    costCents: 3400,
    stock: 100,
    active: true,
    specs: { activeName: "Trenbolone Enanthate 200mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "trestolone-a-100",
    title: "TRESTOLONE A 100",
    shortDescription: "Trestolone Acetate 100mg/ml",
    description: "Trestolone Acetate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 11000,
    costCents: 6600,
    stock: 100,
    active: true,
    specs: { activeName: "Trestolone Acetate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "trestolone-e-100",
    title: "TRESTOLONE E 100",
    shortDescription: "Trestolone Enanthate 100mg/ml",
    description: "Trestolone Enanthate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 11000,
    costCents: 6600,
    stock: 100,
    active: true,
    specs: { activeName: "Trestolone Enanthate 100mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "winimed-50",
    title: "WINIMED 50",
    shortDescription: "Stanozolol 50mg/ml",
    description: "Stanozolol 50mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..",
    category: "iniettabili",
    priceCents: 3600,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "Stanozolol 50mg/ml", packaging: "10 fiale / 1 mL — soluzione sterile I.M." },
  },
  {
    slug: "watermed",
    title: "WATERMED",
    shortDescription: "Acqua batteriostatica 1ml/amp",
    description: "Acqua batteriostatica 1ml/amp. 10 fiale / 1 mL.",
    category: "salute",
    priceCents: 1100,
    costCents: 600,
    stock: 100,
    active: true,
    specs: { activeName: "Acqua batteriostatica 1ml/amp", packaging: "10 fiale / 1 mL" },
  },
  {
    slug: "anadromed-50",
    title: "ANADROMED 50",
    shortDescription: "Oxymetholone 50mg/tab",
    description: "Oxymetholone 50mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 3000,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Oxymetholone 50mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "anavamed-10",
    title: "ANAVAMED 10",
    shortDescription: "Oxandrolone 10mg/tab",
    description: "Oxandrolone 10mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 2500,
    costCents: 1500,
    stock: 100,
    active: true,
    specs: { activeName: "Oxandrolone 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "arimimed-1",
    title: "ARIMIMED 1",
    shortDescription: "Anastrozole 1mg/tab",
    description: "Anastrozole 1mg/tab. 50 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 3000,
    costCents: 900,
    stock: 100,
    active: true,
    specs: { activeName: "Anastrozole 1mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "aromamed-25",
    title: "AROMAMED 25",
    shortDescription: "Exemestane 25mg/tab",
    description: "Exemestane 25mg/tab. 25 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 3300,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Exemestane 25mg/tab", packaging: "25 compresse — uso orale" },
  },
  {
    slug: "cabermed-0-5",
    title: "CABERMED 0.5",
    shortDescription: "Cabergoline 0.5mg/tab",
    description: "Cabergoline 0.5mg/tab. 50 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 6600,
    costCents: 3200,
    stock: 100,
    active: true,
    specs: { activeName: "Cabergoline 0.5mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "ciamed-5",
    title: "CIAMED 5",
    shortDescription: "Tadalafil 5mg/tab",
    description: "Tadalafil 5mg/tab. 50 compresse — uso orale.",
    category: "sex-support",
    priceCents: 2200,
    costCents: 1100,
    stock: 100,
    active: true,
    specs: { activeName: "Tadalafil 5mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "clenomed-40",
    title: "CLENOMED 40",
    shortDescription: "Clenbuterol HCL 40mcg/tab",
    description: "Clenbuterol HCL 40mcg/tab. 50 compresse — uso orale.",
    category: "brucia-grassi",
    priceCents: 1200,
    costCents: 500,
    stock: 100,
    active: true,
    specs: { activeName: "Clenbuterol HCL 40mcg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "clomimed-50",
    title: "CLOMIMED 50",
    shortDescription: "Clomiphene Citrate 50mg/tab",
    description: "Clomiphene Citrate 50mg/tab. 50 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 2300,
    costCents: 1300,
    stock: 100,
    active: true,
    specs: { activeName: "Clomiphene Citrate 50mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "cytomed-25",
    title: "CYTOMED 25",
    shortDescription: "Liothyronine Sodium (T3) 25mcg/tab",
    description: "Liothyronine Sodium (T3) 25mcg/tab. 50 compresse — uso orale.",
    category: "brucia-grassi",
    priceCents: 1300,
    costCents: 500,
    stock: 100,
    active: true,
    specs: { activeName: "Liothyronine Sodium (T3) 25mcg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "dianamed-10",
    title: "DIANAMED 10",
    shortDescription: "Methandienone 10mg/tab",
    description: "Methandienone 10mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 1300,
    costCents: 700,
    stock: 100,
    active: true,
    specs: { activeName: "Methandienone 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "enclomimed-25",
    title: "ENCLOMIMED 25",
    shortDescription: "Enclomiphene Citrate 25mg/tab",
    description: "Enclomiphene Citrate 25mg/tab. 50 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 6600,
    costCents: 3800,
    stock: 100,
    active: true,
    specs: { activeName: "Enclomiphene Citrate 25mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "evimed-60",
    title: "EVIMED 60",
    shortDescription: "Raloxifene HCL 60mg/tab",
    description: "Raloxifene HCL 60mg/tab. 50 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 2800,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "Raloxifene HCL 60mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "ezetimed-10",
    title: "EZETIMED 10",
    shortDescription: "Ezetimibe 10mg/tab",
    description: "Ezetimibe 10mg/tab. 50 compresse — uso orale.",
    category: "salute",
    priceCents: 2800,
    costCents: 1300,
    stock: 100,
    active: true,
    specs: { activeName: "Ezetimibe 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "femamed-2-5",
    title: "FEMAMED 2.5",
    shortDescription: "Letrozole 2.5mg/tab",
    description: "Letrozole 2.5mg/tab. 50 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 3900,
    costCents: 1100,
    stock: 100,
    active: true,
    specs: { activeName: "Letrozole 2.5mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "halomed-5",
    title: "HALOMED 5",
    shortDescription: "Fluoxymesterone 5mg/tab",
    description: "Fluoxymesterone 5mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 5000,
    costCents: 2800,
    stock: 100,
    active: true,
    specs: { activeName: "Fluoxymesterone 5mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "livamed-1",
    title: "LIVAMED 1",
    shortDescription: "Pitavastatin Calcium 1mg/tab",
    description: "Pitavastatin Calcium 1mg/tab. 50 compresse — uso orale.",
    category: "salute",
    priceCents: 2200,
    costCents: 1100,
    stock: 100,
    active: true,
    specs: { activeName: "Pitavastatin Calcium 1mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "nebimed-5",
    title: "NEBIMED 5",
    shortDescription: "Nebivolol 5mg/tab",
    description: "Nebivolol 5mg/tab. 50 compresse — uso orale.",
    category: "salute",
    priceCents: 1700,
    costCents: 900,
    stock: 100,
    active: true,
    specs: { activeName: "Nebivolol 5mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "nolvamed-20",
    title: "NOLVAMED 20",
    shortDescription: "Tamoxifen Citrate 20mg/tab",
    description: "Tamoxifen Citrate 20mg/tab. 50 compresse — uso orale.",
    category: "post-cycle",
    priceCents: 2500,
    costCents: 1200,
    stock: 100,
    active: true,
    specs: { activeName: "Tamoxifen Citrate 20mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "prilimed-30",
    title: "PRILIMED 30",
    shortDescription: "Dapoxetine HCL 30mg/tab",
    description: "Dapoxetine HCL 30mg/tab. 50 compresse — uso orale.",
    category: "sex-support",
    priceCents: 1700,
    costCents: 900,
    stock: 100,
    active: true,
    specs: { activeName: "Dapoxetine HCL 30mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "primomed-25",
    title: "PRIMOMED 25",
    shortDescription: "Methenolone Acetate 25mg/tab",
    description: "Methenolone Acetate 25mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 8300,
    costCents: 4600,
    stock: 100,
    active: true,
    specs: { activeName: "Methenolone Acetate 25mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "provimed-25",
    title: "PROVIMED 25",
    shortDescription: "Mesterolone 25mg/tab",
    description: "Mesterolone 25mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 2500,
    costCents: 1700,
    stock: 100,
    active: true,
    specs: { activeName: "Mesterolone 25mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "supermed-10",
    title: "SUPERMED 10",
    shortDescription: "Methyldrostanolone 10mg/tab",
    description: "Methyldrostanolone 10mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 4500,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "Methyldrostanolone 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "telmimed-40",
    title: "TELMIMED 40",
    shortDescription: "Telmisartan 40mg/tab",
    description: "Telmisartan 40mg/tab. 50 compresse — uso orale.",
    category: "salute",
    priceCents: 2200,
    costCents: 1100,
    stock: 100,
    active: true,
    specs: { activeName: "Telmisartan 40mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "thyromed-50",
    title: "THYROMED 50",
    shortDescription: "Levothyroxine Sodium (T4) 50mcg/tab",
    description: "Levothyroxine Sodium (T4) 50mcg/tab. 50 compresse — uso orale.",
    category: "brucia-grassi",
    priceCents: 1000,
    costCents: 500,
    stock: 100,
    active: true,
    specs: { activeName: "Levothyroxine Sodium (T4) 50mcg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "turimed-10",
    title: "TURIMED 10",
    shortDescription: "Chlorodehydromethyltestosterone 10mg/tab",
    description: "Chlorodehydromethyltestosterone 10mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 1900,
    costCents: 1100,
    stock: 100,
    active: true,
    specs: { activeName: "Chlorodehydromethyltestosterone 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "viamed-20",
    title: "VIAMED 20",
    shortDescription: "Sildenafil Citrate 20mg/tab",
    description: "Sildenafil Citrate 20mg/tab. 50 compresse — uso orale.",
    category: "sex-support",
    priceCents: 1200,
    costCents: 600,
    stock: 100,
    active: true,
    specs: { activeName: "Sildenafil Citrate 20mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "winimed-10",
    title: "WINIMED 10",
    shortDescription: "Stanozolol 10mg/tab",
    description: "Stanozolol 10mg/tab. 50 compresse — uso orale.",
    category: "orali",
    priceCents: 1500,
    costCents: 800,
    stock: 100,
    active: true,
    specs: { activeName: "Stanozolol 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "gw501516-10",
    title: "GW501516 10",
    shortDescription: "Cardarine (GW-501516) 10mg/tab",
    description: "Cardarine (GW-501516) 10mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 4500,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "Cardarine (GW-501516) 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "lgd4033-10",
    title: "LGD4033 10",
    shortDescription: "Ligandrol (LGD-4033) 10mg/tab",
    description: "Ligandrol (LGD-4033) 10mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 6000,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "Ligandrol (LGD-4033) 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "mk2866-10",
    title: "MK2866 10",
    shortDescription: "Ostarine (MK-2866) 10mg/tab",
    description: "Ostarine (MK-2866) 10mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 3300,
    costCents: 2100,
    stock: 100,
    active: true,
    specs: { activeName: "Ostarine (MK-2866) 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "mk677-10",
    title: "MK677 10",
    shortDescription: "Ibutamoren (MK-677) 10mg/tab",
    description: "Ibutamoren (MK-677) 10mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 5000,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "Ibutamoren (MK-677) 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "rad140-10",
    title: "RAD140 10",
    shortDescription: "Testolone (RAD-140) 10mg/tab",
    description: "Testolone (RAD-140) 10mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 5000,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "Testolone (RAD-140) 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "s23-10",
    title: "S23 10",
    shortDescription: "S23 10mg/tab",
    description: "S23 10mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 3500,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "S23 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "s4-25",
    title: "S4 25",
    shortDescription: "Andarine (S4) 25mg/tab",
    description: "Andarine (S4) 25mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 4500,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "Andarine (S4) 25mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "sr9009-10",
    title: "SR9009 10",
    shortDescription: "Stenabolic (SR9009) 10mg/tab",
    description: "Stenabolic (SR9009) 10mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 3500,
    costCents: 2100,
    stock: 100,
    active: true,
    specs: { activeName: "Stenabolic (SR9009) 10mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "yk11-5",
    title: "YK11 5",
    shortDescription: "YK11 5mg/tab",
    description: "YK11 5mg/tab. 50 compresse — uso orale.",
    category: "sarms",
    priceCents: 5500,
    costCents: 2100,
    stock: 100,
    active: true,
    specs: { activeName: "YK11 5mg/tab", packaging: "50 compresse — uso orale" },
  },
  {
    slug: "bpc-157",
    title: "BPC 157",
    shortDescription: "BPC-157 Pentadecapeptide 5mg/vial",
    description: "BPC-157 Pentadecapeptide 5mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3500,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "BPC-157 Pentadecapeptide 5mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "cjc-1295-dac",
    title: "CJC-1295 DAC",
    shortDescription: "CJC-1295 DAC 2mg/vial",
    description: "CJC-1295 DAC 2mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3000,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "CJC-1295 DAC 2mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "deustropin-4-12",
    title: "DEUSTROPIN 4/12",
    shortDescription: "Somatropina (hGH ricombinante) 4mg (12IU)/vial",
    description: "Somatropina (hGH ricombinante) 4mg (12IU)/vial. 10 flaconcini / 4 mg (12IU).",
    category: "hgh-peptidi",
    priceCents: 19000,
    costCents: 15500,
    stock: 100,
    active: true,
    specs: { activeName: "Somatropina (hGH ricombinante) 4mg (12IU)/vial", packaging: "10 flaconcini / 4 mg (12IU)" },
  },
  {
    slug: "deustropin-pen-10",
    title: "DEUSTROPIN PEN 10",
    shortDescription: "Somatropina (hGH ricombinante) 10mg/pen",
    description: "Somatropina (hGH ricombinante) 10mg/pen. cartuccia 1.5ml / 10 mg (30IU).",
    category: "hgh-peptidi",
    priceCents: 0,
    costCents: 0,
    stock: 100,
    active: true,
    specs: { activeName: "Somatropina (hGH ricombinante) 10mg/pen", packaging: "cartuccia 1.5ml / 10 mg (30IU)" },
  },
  {
    slug: "deustropin-pen-15",
    title: "DEUSTROPIN PEN 15",
    shortDescription: "Somatropina (hGH ricombinante) 15mg/pen",
    description: "Somatropina (hGH ricombinante) 15mg/pen. cartuccia 1.5ml / 15 mg (45IU).",
    category: "hgh-peptidi",
    priceCents: 0,
    costCents: 0,
    stock: 100,
    active: true,
    specs: { activeName: "Somatropina (hGH ricombinante) 15mg/pen", packaging: "cartuccia 1.5ml / 15 mg (45IU)" },
  },
  {
    slug: "dsip",
    title: "DSIP",
    shortDescription: "Delta Sleep-inducing Peptide 5mg/vial",
    description: "Delta Sleep-inducing Peptide 5mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3500,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Delta Sleep-inducing Peptide 5mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "epithalon",
    title: "EPITHALON",
    shortDescription: "Epithalamine 10mg/vial",
    description: "Epithalamine 10mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3000,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Epithalamine 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "epo",
    title: "EPO",
    shortDescription: "Erythropoietin 3000IU/vial",
    description: "Erythropoietin 3000IU/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 0,
    costCents: 0,
    stock: 100,
    active: true,
    specs: { activeName: "Erythropoietin 3000IU/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "follistatin",
    title: "FOLLISTATIN",
    shortDescription: "Activin-binding protein 1mg/vial",
    description: "Activin-binding protein 1mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 6000,
    costCents: 2600,
    stock: 100,
    active: true,
    specs: { activeName: "Activin-binding protein 1mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "ghk-cu",
    title: "GHK-CU",
    shortDescription: "GHK-Cu Copper Tripeptide-1 50mg/vial",
    description: "GHK-Cu Copper Tripeptide-1 50mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 5000,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "GHK-Cu Copper Tripeptide-1 50mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "ghrp-2",
    title: "GHRP-2",
    shortDescription: "Growth Hormone-Releasing Peptide 2 10mg/vial",
    description: "Growth Hormone-Releasing Peptide 2 10mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3500,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "Growth Hormone-Releasing Peptide 2 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "ghrp-6",
    title: "GHRP-6",
    shortDescription: "Growth Hormone-Releasing Peptide 6 10mg/vial",
    description: "Growth Hormone-Releasing Peptide 6 10mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3500,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "Growth Hormone-Releasing Peptide 6 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "hcg",
    title: "HCG",
    shortDescription: "Human Chorionic Gonadotropin 5000IU/vial",
    description: "Human Chorionic Gonadotropin 5000IU/vial. 1 flaconcino.",
    category: "post-cycle",
    priceCents: 4000,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "Human Chorionic Gonadotropin 5000IU/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "hexarelin",
    title: "HEXARELIN",
    shortDescription: "Hexarelin 2mg/vial",
    description: "Hexarelin 2mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3000,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Hexarelin 2mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "hgh-fragment-176-191",
    title: "HGH FRAGMENT 176-191",
    shortDescription: "hGH Fragment 176-191 5mg/vial",
    description: "hGH Fragment 176-191 5mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 4000,
    costCents: 1900,
    stock: 100,
    active: true,
    specs: { activeName: "hGH Fragment 176-191 5mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "hmg",
    title: "HMG",
    shortDescription: "Human Menopausal Gonadotropin 0.15mg/vial",
    description: "Human Menopausal Gonadotropin 0.15mg/vial. 1 flaconcino.",
    category: "post-cycle",
    priceCents: 4000,
    costCents: 2100,
    stock: 100,
    active: true,
    specs: { activeName: "Human Menopausal Gonadotropin 0.15mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "igf-1-des",
    title: "IGF-1 DES",
    shortDescription: "Insulin-like growth factor 1, DES 1mg/vial",
    description: "Insulin-like growth factor 1, DES 1mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 0,
    costCents: 0,
    stock: 100,
    active: true,
    specs: { activeName: "Insulin-like growth factor 1, DES 1mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "igf-1-lr3",
    title: "IGF-1 LR3",
    shortDescription: "Long arginine 3-IGF-1 1mg/vial",
    description: "Long arginine 3-IGF-1 1mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 0,
    costCents: 0,
    stock: 100,
    active: true,
    specs: { activeName: "Long arginine 3-IGF-1 1mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "ipamorelin",
    title: "IPAMORELIN",
    shortDescription: "Ipamorelin 2mg/vial",
    description: "Ipamorelin 2mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 2000,
    costCents: 1100,
    stock: 100,
    active: true,
    specs: { activeName: "Ipamorelin 2mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "melanotan-ii",
    title: "MELANOTAN II",
    shortDescription: "Melanotan II 10mg/vial",
    description: "Melanotan II 10mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3000,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Melanotan II 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "mod-grf-1-29",
    title: "MOD GRF 1-29",
    shortDescription: "Mod GRF 1-29 2mg/vial",
    description: "Mod GRF 1-29 2mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 2000,
    costCents: 1100,
    stock: 100,
    active: true,
    specs: { activeName: "Mod GRF 1-29 2mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "mots-c",
    title: "MOTS-C",
    shortDescription: "MOTS-c Mitochondrial-Derived Peptide 10mg/vial",
    description: "MOTS-c Mitochondrial-Derived Peptide 10mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 5000,
    costCents: 2700,
    stock: 100,
    active: true,
    specs: { activeName: "MOTS-c Mitochondrial-Derived Peptide 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "peg-mgf",
    title: "PEG MGF",
    shortDescription: "Pegylated Mechano Growth Factor 2mg/vial",
    description: "Pegylated Mechano Growth Factor 2mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3300,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Pegylated Mechano Growth Factor 2mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "pnc-27",
    title: "PNC-27",
    shortDescription: "PNC-27 Anti-cancer Peptide 5mg/vial",
    description: "PNC-27 Anti-cancer Peptide 5mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 5000,
    costCents: 3200,
    stock: 100,
    active: true,
    specs: { activeName: "PNC-27 Anti-cancer Peptide 5mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "pt-141",
    title: "PT-141",
    shortDescription: "Bremelanotide (PT-141) 10mg/vial",
    description: "Bremelanotide (PT-141) 10mg/vial. 1 flaconcino.",
    category: "sex-support",
    priceCents: 3000,
    costCents: 1600,
    stock: 100,
    active: true,
    specs: { activeName: "Bremelanotide (PT-141) 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "retatrutide",
    title: "RETATRUTIDE",
    shortDescription: "Retatrutide (GIP/GLP-1/Glucagon) 10mg/vial",
    description: "Retatrutide (GIP/GLP-1/Glucagon) 10mg/vial. 1 flaconcino.",
    category: "brucia-grassi",
    priceCents: 9000,
    costCents: 4700,
    stock: 100,
    active: true,
    specs: { activeName: "Retatrutide (GIP/GLP-1/Glucagon) 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "selank",
    title: "SELANK",
    shortDescription: "Selank Anxiolytic Peptide 5mg/vial",
    description: "Selank Anxiolytic Peptide 5mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 1500,
    costCents: 900,
    stock: 100,
    active: true,
    specs: { activeName: "Selank Anxiolytic Peptide 5mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "semaglutide",
    title: "SEMAGLUTIDE",
    shortDescription: "Semaglutide (GLP-1) 5mg/vial",
    description: "Semaglutide (GLP-1) 5mg/vial. 1 flaconcino.",
    category: "brucia-grassi",
    priceCents: 7000,
    costCents: 3200,
    stock: 100,
    active: true,
    specs: { activeName: "Semaglutide (GLP-1) 5mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "semax",
    title: "SEMAX",
    shortDescription: "Semax Heptapeptide 5mg/vial",
    description: "Semax Heptapeptide 5mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 1500,
    costCents: 900,
    stock: 100,
    active: true,
    specs: { activeName: "Semax Heptapeptide 5mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "tb-500",
    title: "TB 500",
    shortDescription: "Thymosin Beta-4 (TB-500) 2mg/vial",
    description: "Thymosin Beta-4 (TB-500) 2mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 3000,
    costCents: 1500,
    stock: 100,
    active: true,
    specs: { activeName: "Thymosin Beta-4 (TB-500) 2mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "tirzepatide",
    title: "TIRZEPATIDE",
    shortDescription: "Tirzepatide (GIP/GLP-1) 10mg/vial",
    description: "Tirzepatide (GIP/GLP-1) 10mg/vial. 1 flaconcino.",
    category: "brucia-grassi",
    priceCents: 8000,
    costCents: 4200,
    stock: 100,
    active: true,
    specs: { activeName: "Tirzepatide (GIP/GLP-1) 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "thymalin",
    title: "THYMALIN",
    shortDescription: "Thymalin Thymic factor 10mg/vial",
    description: "Thymalin Thymic factor 10mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 2500,
    costCents: 1300,
    stock: 100,
    active: true,
    specs: { activeName: "Thymalin Thymic factor 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "thymosin-a1",
    title: "THYMOSIN A1",
    shortDescription: "Thymosin Alpha-1 10mg/vial",
    description: "Thymosin Alpha-1 10mg/vial. 1 flaconcino.",
    category: "hgh-peptidi",
    priceCents: 6000,
    costCents: 3700,
    stock: 100,
    active: true,
    specs: { activeName: "Thymosin Alpha-1 10mg/vial", packaging: "1 flaconcino" },
  },
  {
    slug: "viamed-100",
    title: "VIAMED 100",
    shortDescription: "Sildenafil 100mg",
    description: "Sildenafil 100mg. 7 bustine / 100 mg — uso orale.",
    category: "sex-support",
    priceCents: 1700,
    costCents: 800,
    stock: 100,
    active: true,
    specs: { activeName: "Sildenafil 100mg", packaging: "7 bustine / 100 mg — uso orale" },
  },
];
