-- Kratos Labs — catalogo Deus Medical (categorie + prodotti + prezzo di acquisto).
-- Esegui nel dashboard Supabase: SQL Editor -> New query -> Run.
-- Prezzi: price_cents = RETAIL (vendita), cost_cents = DROP SHIPPING (acquisto).

-- 1) Colonna costo per il calcolo dei profitti.
alter table public.products
  add column if not exists cost_cents integer not null default 0 check (cost_cents >= 0);

-- 2) Rimuove le vecchie categorie di esempio (i prodotti collegati restano, senza categoria).
delete from public.categories
  where slug in ('proteine','creatina','pre-workout','elettroliti','omega-3','vitamine');

-- 3) Nuove categorie del listino Deus Medical.
insert into public.categories (slug, name, description, position) values
  ('iniettabili', 'Iniettabili', 'Soluzioni sterili in fiale per uso intramuscolare.', 1),
  ('orali', 'Orali', 'Compresse in blister per uso orale.', 2),
  ('post-cycle', 'Post Cycle (PCT)', 'SERM, inibitori dell''aromatasi e supporto ormonale.', 3),
  ('brucia-grassi', 'Brucia grassi', 'Termogenici, ormoni tiroidei e agonisti GLP-1.', 4),
  ('sex-support', 'Sex Support', 'Supporto per la funzione sessuale.', 5),
  ('hgh-peptidi', 'HGH & Peptidi', 'Ormone della crescita e peptidi.', 6),
  ('sarms', 'SARMs', 'Modulatori selettivi del recettore degli androgeni.', 7),
  ('salute', 'Salute', 'Supporto cardiovascolare, colesterolo e accessori.', 8)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, position = excluded.position, active = true;

-- 4) Prodotti. price_cents = vendita (RETAIL), cost_cents = acquisto (DROP SHIPPING).
--    I prodotti senza prezzo nel listino sono caricati come non attivi (stock 0).
insert into public.products
  (slug, brand, title, short_description, description, category, price_cents, cost_cents, stock, active, specs)
values
  ('3-trenbomed-150', 'Deus Medical', '3-TRENBOMED 150', 'Trenbolone Hexahydrobenzylcarbonate / Enanthate / Acetate 50mg/ml', 'Trenbolone Hexahydrobenzylcarbonate / Enanthate / Acetate 50mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 5700, 3500, 100, true, '{"activeName": "Trenbolone Hexahydrobenzylcarbonate / Enanthate / Acetate 50mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('decamed-250', 'Deus Medical', 'DECAMED 250', 'Nandrolone Decanoate 250mg/ml', 'Nandrolone Decanoate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 4500, 2200, 100, true, '{"activeName": "Nandrolone Decanoate 250mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('decamed-pp-100', 'Deus Medical', 'DECAMED PP 100', 'Nandrolone Phenylpropionate 100mg/ml', 'Nandrolone Phenylpropionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 3400, 1800, 100, true, '{"activeName": "Nandrolone Phenylpropionate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('dhb-med-100', 'Deus Medical', 'DHB-MED 100', 'Dihydroboldenone Cypionate 100mg/ml', 'Dihydroboldenone Cypionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 5500, 2700, 100, true, '{"activeName": "Dihydroboldenone Cypionate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('dianamed-100', 'Deus Medical', 'DIANAMED 100', 'Methandienone 100mg/ml', 'Methandienone 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 4000, 1700, 100, true, '{"activeName": "Methandienone 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('equimed-250', 'Deus Medical', 'EQUIMED 250', 'Boldenone Undecylenate 250mg/ml', 'Boldenone Undecylenate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 4200, 2000, 100, true, '{"activeName": "Boldenone Undecylenate 250mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('mastermed-e-200', 'Deus Medical', 'MASTERMED E 200', 'Drostanolone Enanthate 200mg/ml', 'Drostanolone Enanthate 200mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 5500, 3500, 100, true, '{"activeName": "Drostanolone Enanthate 200mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('mastermed-p-100', 'Deus Medical', 'MASTERMED P 100', 'Drostanolone Propionate 100mg/ml', 'Drostanolone Propionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 4400, 2300, 100, true, '{"activeName": "Drostanolone Propionate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('paramed-76-5', 'Deus Medical', 'PARAMED 76.5', 'Trenbolone Hexahydrobenzylcarbonate 76.5mg/ml', 'Trenbolone Hexahydrobenzylcarbonate 76.5mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 5500, 3900, 100, true, '{"activeName": "Trenbolone Hexahydrobenzylcarbonate 76.5mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('primomed-100', 'Deus Medical', 'PRIMOMED 100', 'Methenolone Enanthate 100mg/ml', 'Methenolone Enanthate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 7000, 4700, 100, true, '{"activeName": "Methenolone Enanthate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('sustamed-250', 'Deus Medical', 'SUSTAMED 250', 'Testosterone Phenylpropionate/Decanoate/Isocaproate/Propionate 250mg/ml', 'Testosterone Phenylpropionate/Decanoate/Isocaproate/Propionate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 3700, 1900, 100, true, '{"activeName": "Testosterone Phenylpropionate/Decanoate/Isocaproate/Propionate 250mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('testomed-100', 'Deus Medical', 'TESTOMED 100', 'Testosterone Base 100mg/ml', 'Testosterone Base 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 3100, 1400, 100, true, '{"activeName": "Testosterone Base 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('testomed-c-250', 'Deus Medical', 'TESTOMED C 250', 'Testosterone Cypionate 250mg/ml', 'Testosterone Cypionate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 3500, 1700, 100, true, '{"activeName": "Testosterone Cypionate 250mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('testomed-e-250', 'Deus Medical', 'TESTOMED E 250', 'Testosterone Enanthate 250mg/ml', 'Testosterone Enanthate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 3500, 1700, 100, true, '{"activeName": "Testosterone Enanthate 250mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('testomed-p-100', 'Deus Medical', 'TESTOMED P 100', 'Testosterone Propionate 100mg/ml', 'Testosterone Propionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 2900, 1300, 100, true, '{"activeName": "Testosterone Propionate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('testomed-pp-100', 'Deus Medical', 'TESTOMED PP 100', 'Testosterone Phenylpropionate 100mg/ml', 'Testosterone Phenylpropionate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 2900, 1300, 100, true, '{"activeName": "Testosterone Phenylpropionate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('testomed-u-250', 'Deus Medical', 'TESTOMED U 250', 'Testosterone Undecanoate 250mg/ml', 'Testosterone Undecanoate 250mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 3300, 1600, 100, true, '{"activeName": "Testosterone Undecanoate 250mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('trenbomed-a-100', 'Deus Medical', 'TRENBOMED A 100', 'Trenbolone Acetate 100mg/ml', 'Trenbolone Acetate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 4900, 2700, 100, true, '{"activeName": "Trenbolone Acetate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('trenbomed-e-200', 'Deus Medical', 'TRENBOMED E 200', 'Trenbolone Enanthate 200mg/ml', 'Trenbolone Enanthate 200mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 5500, 3400, 100, true, '{"activeName": "Trenbolone Enanthate 200mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('trestolone-a-100', 'Deus Medical', 'TRESTOLONE A 100', 'Trestolone Acetate 100mg/ml', 'Trestolone Acetate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 11000, 6600, 100, true, '{"activeName": "Trestolone Acetate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('trestolone-e-100', 'Deus Medical', 'TRESTOLONE E 100', 'Trestolone Enanthate 100mg/ml', 'Trestolone Enanthate 100mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 11000, 6600, 100, true, '{"activeName": "Trestolone Enanthate 100mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('winimed-50', 'Deus Medical', 'WINIMED 50', 'Stanozolol 50mg/ml', 'Stanozolol 50mg/ml. 10 fiale / 1 mL — soluzione sterile I.M..', 'iniettabili', 3600, 1900, 100, true, '{"activeName": "Stanozolol 50mg/ml", "packaging": "10 fiale / 1 mL — soluzione sterile I.M."}'::jsonb),
  ('watermed', 'Deus Medical', 'WATERMED', 'Acqua batteriostatica 1ml/amp', 'Acqua batteriostatica 1ml/amp. 10 fiale / 1 mL.', 'salute', 1100, 600, 100, true, '{"activeName": "Acqua batteriostatica 1ml/amp", "packaging": "10 fiale / 1 mL"}'::jsonb),
  ('anadromed-50', 'Deus Medical', 'ANADROMED 50', 'Oxymetholone 50mg/tab', 'Oxymetholone 50mg/tab. 50 compresse — uso orale.', 'orali', 3000, 1600, 100, true, '{"activeName": "Oxymetholone 50mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('anavamed-10', 'Deus Medical', 'ANAVAMED 10', 'Oxandrolone 10mg/tab', 'Oxandrolone 10mg/tab. 50 compresse — uso orale.', 'orali', 2500, 1500, 100, true, '{"activeName": "Oxandrolone 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('arimimed-1', 'Deus Medical', 'ARIMIMED 1', 'Anastrozole 1mg/tab', 'Anastrozole 1mg/tab. 50 compresse — uso orale.', 'post-cycle', 3000, 900, 100, true, '{"activeName": "Anastrozole 1mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('aromamed-25', 'Deus Medical', 'AROMAMED 25', 'Exemestane 25mg/tab', 'Exemestane 25mg/tab. 25 compresse — uso orale.', 'post-cycle', 3300, 1600, 100, true, '{"activeName": "Exemestane 25mg/tab", "packaging": "25 compresse — uso orale"}'::jsonb),
  ('cabermed-0-5', 'Deus Medical', 'CABERMED 0.5', 'Cabergoline 0.5mg/tab', 'Cabergoline 0.5mg/tab. 50 compresse — uso orale.', 'post-cycle', 6600, 3200, 100, true, '{"activeName": "Cabergoline 0.5mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('ciamed-5', 'Deus Medical', 'CIAMED 5', 'Tadalafil 5mg/tab', 'Tadalafil 5mg/tab. 50 compresse — uso orale.', 'sex-support', 2200, 1100, 100, true, '{"activeName": "Tadalafil 5mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('clenomed-40', 'Deus Medical', 'CLENOMED 40', 'Clenbuterol HCL 40mcg/tab', 'Clenbuterol HCL 40mcg/tab. 50 compresse — uso orale.', 'brucia-grassi', 1200, 500, 100, true, '{"activeName": "Clenbuterol HCL 40mcg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('clomimed-50', 'Deus Medical', 'CLOMIMED 50', 'Clomiphene Citrate 50mg/tab', 'Clomiphene Citrate 50mg/tab. 50 compresse — uso orale.', 'post-cycle', 2300, 1300, 100, true, '{"activeName": "Clomiphene Citrate 50mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('cytomed-25', 'Deus Medical', 'CYTOMED 25', 'Liothyronine Sodium (T3) 25mcg/tab', 'Liothyronine Sodium (T3) 25mcg/tab. 50 compresse — uso orale.', 'brucia-grassi', 1300, 500, 100, true, '{"activeName": "Liothyronine Sodium (T3) 25mcg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('dianamed-10', 'Deus Medical', 'DIANAMED 10', 'Methandienone 10mg/tab', 'Methandienone 10mg/tab. 50 compresse — uso orale.', 'orali', 1300, 700, 100, true, '{"activeName": "Methandienone 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('enclomimed-25', 'Deus Medical', 'ENCLOMIMED 25', 'Enclomiphene Citrate 25mg/tab', 'Enclomiphene Citrate 25mg/tab. 50 compresse — uso orale.', 'post-cycle', 6600, 3800, 100, true, '{"activeName": "Enclomiphene Citrate 25mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('evimed-60', 'Deus Medical', 'EVIMED 60', 'Raloxifene HCL 60mg/tab', 'Raloxifene HCL 60mg/tab. 50 compresse — uso orale.', 'post-cycle', 2800, 1900, 100, true, '{"activeName": "Raloxifene HCL 60mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('ezetimed-10', 'Deus Medical', 'EZETIMED 10', 'Ezetimibe 10mg/tab', 'Ezetimibe 10mg/tab. 50 compresse — uso orale.', 'salute', 2800, 1300, 100, true, '{"activeName": "Ezetimibe 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('femamed-2-5', 'Deus Medical', 'FEMAMED 2.5', 'Letrozole 2.5mg/tab', 'Letrozole 2.5mg/tab. 50 compresse — uso orale.', 'post-cycle', 3900, 1100, 100, true, '{"activeName": "Letrozole 2.5mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('halomed-5', 'Deus Medical', 'HALOMED 5', 'Fluoxymesterone 5mg/tab', 'Fluoxymesterone 5mg/tab. 50 compresse — uso orale.', 'orali', 5000, 2800, 100, true, '{"activeName": "Fluoxymesterone 5mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('livamed-1', 'Deus Medical', 'LIVAMED 1', 'Pitavastatin Calcium 1mg/tab', 'Pitavastatin Calcium 1mg/tab. 50 compresse — uso orale.', 'salute', 2200, 1100, 100, true, '{"activeName": "Pitavastatin Calcium 1mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('nebimed-5', 'Deus Medical', 'NEBIMED 5', 'Nebivolol 5mg/tab', 'Nebivolol 5mg/tab. 50 compresse — uso orale.', 'salute', 1700, 900, 100, true, '{"activeName": "Nebivolol 5mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('nolvamed-20', 'Deus Medical', 'NOLVAMED 20', 'Tamoxifen Citrate 20mg/tab', 'Tamoxifen Citrate 20mg/tab. 50 compresse — uso orale.', 'post-cycle', 2500, 1200, 100, true, '{"activeName": "Tamoxifen Citrate 20mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('prilimed-30', 'Deus Medical', 'PRILIMED 30', 'Dapoxetine HCL 30mg/tab', 'Dapoxetine HCL 30mg/tab. 50 compresse — uso orale.', 'sex-support', 1700, 900, 100, true, '{"activeName": "Dapoxetine HCL 30mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('primomed-25', 'Deus Medical', 'PRIMOMED 25', 'Methenolone Acetate 25mg/tab', 'Methenolone Acetate 25mg/tab. 50 compresse — uso orale.', 'orali', 8300, 4600, 100, true, '{"activeName": "Methenolone Acetate 25mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('provimed-25', 'Deus Medical', 'PROVIMED 25', 'Mesterolone 25mg/tab', 'Mesterolone 25mg/tab. 50 compresse — uso orale.', 'orali', 2500, 1700, 100, true, '{"activeName": "Mesterolone 25mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('supermed-10', 'Deus Medical', 'SUPERMED 10', 'Methyldrostanolone 10mg/tab', 'Methyldrostanolone 10mg/tab. 50 compresse — uso orale.', 'orali', 4500, 1900, 100, true, '{"activeName": "Methyldrostanolone 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('telmimed-40', 'Deus Medical', 'TELMIMED 40', 'Telmisartan 40mg/tab', 'Telmisartan 40mg/tab. 50 compresse — uso orale.', 'salute', 2200, 1100, 100, true, '{"activeName": "Telmisartan 40mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('thyromed-50', 'Deus Medical', 'THYROMED 50', 'Levothyroxine Sodium (T4) 50mcg/tab', 'Levothyroxine Sodium (T4) 50mcg/tab. 50 compresse — uso orale.', 'brucia-grassi', 1000, 500, 100, true, '{"activeName": "Levothyroxine Sodium (T4) 50mcg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('turimed-10', 'Deus Medical', 'TURIMED 10', 'Chlorodehydromethyltestosterone 10mg/tab', 'Chlorodehydromethyltestosterone 10mg/tab. 50 compresse — uso orale.', 'orali', 1900, 1100, 100, true, '{"activeName": "Chlorodehydromethyltestosterone 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('viamed-20', 'Deus Medical', 'VIAMED 20', 'Sildenafil Citrate 20mg/tab', 'Sildenafil Citrate 20mg/tab. 50 compresse — uso orale.', 'sex-support', 1200, 600, 100, true, '{"activeName": "Sildenafil Citrate 20mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('winimed-10', 'Deus Medical', 'WINIMED 10', 'Stanozolol 10mg/tab', 'Stanozolol 10mg/tab. 50 compresse — uso orale.', 'orali', 1500, 800, 100, true, '{"activeName": "Stanozolol 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('gw501516-10', 'Deus Medical', 'GW501516 10', 'Cardarine (GW-501516) 10mg/tab', 'Cardarine (GW-501516) 10mg/tab. 50 compresse — uso orale.', 'sarms', 4500, 2700, 100, true, '{"activeName": "Cardarine (GW-501516) 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('lgd4033-10', 'Deus Medical', 'LGD4033 10', 'Ligandrol (LGD-4033) 10mg/tab', 'Ligandrol (LGD-4033) 10mg/tab. 50 compresse — uso orale.', 'sarms', 6000, 2700, 100, true, '{"activeName": "Ligandrol (LGD-4033) 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('mk2866-10', 'Deus Medical', 'MK2866 10', 'Ostarine (MK-2866) 10mg/tab', 'Ostarine (MK-2866) 10mg/tab. 50 compresse — uso orale.', 'sarms', 3300, 2100, 100, true, '{"activeName": "Ostarine (MK-2866) 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('mk677-10', 'Deus Medical', 'MK677 10', 'Ibutamoren (MK-677) 10mg/tab', 'Ibutamoren (MK-677) 10mg/tab. 50 compresse — uso orale.', 'sarms', 5000, 2700, 100, true, '{"activeName": "Ibutamoren (MK-677) 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('rad140-10', 'Deus Medical', 'RAD140 10', 'Testolone (RAD-140) 10mg/tab', 'Testolone (RAD-140) 10mg/tab. 50 compresse — uso orale.', 'sarms', 5000, 2700, 100, true, '{"activeName": "Testolone (RAD-140) 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('s23-10', 'Deus Medical', 'S23 10', 'S23 10mg/tab', 'S23 10mg/tab. 50 compresse — uso orale.', 'sarms', 3500, 1900, 100, true, '{"activeName": "S23 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('s4-25', 'Deus Medical', 'S4 25', 'Andarine (S4) 25mg/tab', 'Andarine (S4) 25mg/tab. 50 compresse — uso orale.', 'sarms', 4500, 2700, 100, true, '{"activeName": "Andarine (S4) 25mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('sr9009-10', 'Deus Medical', 'SR9009 10', 'Stenabolic (SR9009) 10mg/tab', 'Stenabolic (SR9009) 10mg/tab. 50 compresse — uso orale.', 'sarms', 3500, 2100, 100, true, '{"activeName": "Stenabolic (SR9009) 10mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('yk11-5', 'Deus Medical', 'YK11 5', 'YK11 5mg/tab', 'YK11 5mg/tab. 50 compresse — uso orale.', 'sarms', 5500, 2100, 100, true, '{"activeName": "YK11 5mg/tab", "packaging": "50 compresse — uso orale"}'::jsonb),
  ('bpc-157', 'Deus Medical', 'BPC 157', 'BPC-157 Pentadecapeptide 5mg/vial', 'BPC-157 Pentadecapeptide 5mg/vial. 1 flaconcino.', 'hgh-peptidi', 3500, 1600, 100, true, '{"activeName": "BPC-157 Pentadecapeptide 5mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('cjc-1295-dac', 'Deus Medical', 'CJC-1295 DAC', 'CJC-1295 DAC 2mg/vial', 'CJC-1295 DAC 2mg/vial. 1 flaconcino.', 'hgh-peptidi', 3000, 1600, 100, true, '{"activeName": "CJC-1295 DAC 2mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('deustropin-4-12', 'Deus Medical', 'DEUSTROPIN 4/12', 'Somatropina (hGH ricombinante) 4mg (12IU)/vial', 'Somatropina (hGH ricombinante) 4mg (12IU)/vial. 10 flaconcini / 4 mg (12IU).', 'hgh-peptidi', 19000, 15500, 100, true, '{"activeName": "Somatropina (hGH ricombinante) 4mg (12IU)/vial", "packaging": "10 flaconcini / 4 mg (12IU)"}'::jsonb),
  ('deustropin-pen-10', 'Deus Medical', 'DEUSTROPIN PEN 10', 'Somatropina (hGH ricombinante) 10mg/pen', 'Somatropina (hGH ricombinante) 10mg/pen. cartuccia 1.5ml / 10 mg (30IU).', 'hgh-peptidi', 0, 0, 100, true, '{"activeName": "Somatropina (hGH ricombinante) 10mg/pen", "packaging": "cartuccia 1.5ml / 10 mg (30IU)"}'::jsonb),
  ('deustropin-pen-15', 'Deus Medical', 'DEUSTROPIN PEN 15', 'Somatropina (hGH ricombinante) 15mg/pen', 'Somatropina (hGH ricombinante) 15mg/pen. cartuccia 1.5ml / 15 mg (45IU).', 'hgh-peptidi', 0, 0, 100, true, '{"activeName": "Somatropina (hGH ricombinante) 15mg/pen", "packaging": "cartuccia 1.5ml / 15 mg (45IU)"}'::jsonb),
  ('dsip', 'Deus Medical', 'DSIP', 'Delta Sleep-inducing Peptide 5mg/vial', 'Delta Sleep-inducing Peptide 5mg/vial. 1 flaconcino.', 'hgh-peptidi', 3500, 1600, 100, true, '{"activeName": "Delta Sleep-inducing Peptide 5mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('epithalon', 'Deus Medical', 'EPITHALON', 'Epithalamine 10mg/vial', 'Epithalamine 10mg/vial. 1 flaconcino.', 'hgh-peptidi', 3000, 1600, 100, true, '{"activeName": "Epithalamine 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('epo', 'Deus Medical', 'EPO', 'Erythropoietin 3000IU/vial', 'Erythropoietin 3000IU/vial. 1 flaconcino.', 'hgh-peptidi', 0, 0, 100, true, '{"activeName": "Erythropoietin 3000IU/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('follistatin', 'Deus Medical', 'FOLLISTATIN', 'Activin-binding protein 1mg/vial', 'Activin-binding protein 1mg/vial. 1 flaconcino.', 'hgh-peptidi', 6000, 2600, 100, true, '{"activeName": "Activin-binding protein 1mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('ghk-cu', 'Deus Medical', 'GHK-CU', 'GHK-Cu Copper Tripeptide-1 50mg/vial', 'GHK-Cu Copper Tripeptide-1 50mg/vial. 1 flaconcino.', 'hgh-peptidi', 5000, 2700, 100, true, '{"activeName": "GHK-Cu Copper Tripeptide-1 50mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('ghrp-2', 'Deus Medical', 'GHRP-2', 'Growth Hormone-Releasing Peptide 2 10mg/vial', 'Growth Hormone-Releasing Peptide 2 10mg/vial. 1 flaconcino.', 'hgh-peptidi', 3500, 1900, 100, true, '{"activeName": "Growth Hormone-Releasing Peptide 2 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('ghrp-6', 'Deus Medical', 'GHRP-6', 'Growth Hormone-Releasing Peptide 6 10mg/vial', 'Growth Hormone-Releasing Peptide 6 10mg/vial. 1 flaconcino.', 'hgh-peptidi', 3500, 1900, 100, true, '{"activeName": "Growth Hormone-Releasing Peptide 6 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('hcg', 'Deus Medical', 'HCG', 'Human Chorionic Gonadotropin 5000IU/vial', 'Human Chorionic Gonadotropin 5000IU/vial. 1 flaconcino.', 'post-cycle', 4000, 1900, 100, true, '{"activeName": "Human Chorionic Gonadotropin 5000IU/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('hexarelin', 'Deus Medical', 'HEXARELIN', 'Hexarelin 2mg/vial', 'Hexarelin 2mg/vial. 1 flaconcino.', 'hgh-peptidi', 3000, 1600, 100, true, '{"activeName": "Hexarelin 2mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('hgh-fragment-176-191', 'Deus Medical', 'HGH FRAGMENT 176-191', 'hGH Fragment 176-191 5mg/vial', 'hGH Fragment 176-191 5mg/vial. 1 flaconcino.', 'hgh-peptidi', 4000, 1900, 100, true, '{"activeName": "hGH Fragment 176-191 5mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('hmg', 'Deus Medical', 'HMG', 'Human Menopausal Gonadotropin 0.15mg/vial', 'Human Menopausal Gonadotropin 0.15mg/vial. 1 flaconcino.', 'post-cycle', 4000, 2100, 100, true, '{"activeName": "Human Menopausal Gonadotropin 0.15mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('igf-1-des', 'Deus Medical', 'IGF-1 DES', 'Insulin-like growth factor 1, DES 1mg/vial', 'Insulin-like growth factor 1, DES 1mg/vial. 1 flaconcino.', 'hgh-peptidi', 0, 0, 100, true, '{"activeName": "Insulin-like growth factor 1, DES 1mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('igf-1-lr3', 'Deus Medical', 'IGF-1 LR3', 'Long arginine 3-IGF-1 1mg/vial', 'Long arginine 3-IGF-1 1mg/vial. 1 flaconcino.', 'hgh-peptidi', 0, 0, 100, true, '{"activeName": "Long arginine 3-IGF-1 1mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('ipamorelin', 'Deus Medical', 'IPAMORELIN', 'Ipamorelin 2mg/vial', 'Ipamorelin 2mg/vial. 1 flaconcino.', 'hgh-peptidi', 2000, 1100, 100, true, '{"activeName": "Ipamorelin 2mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('melanotan-ii', 'Deus Medical', 'MELANOTAN II', 'Melanotan II 10mg/vial', 'Melanotan II 10mg/vial. 1 flaconcino.', 'hgh-peptidi', 3000, 1600, 100, true, '{"activeName": "Melanotan II 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('mod-grf-1-29', 'Deus Medical', 'MOD GRF 1-29', 'Mod GRF 1-29 2mg/vial', 'Mod GRF 1-29 2mg/vial. 1 flaconcino.', 'hgh-peptidi', 2000, 1100, 100, true, '{"activeName": "Mod GRF 1-29 2mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('mots-c', 'Deus Medical', 'MOTS-C', 'MOTS-c Mitochondrial-Derived Peptide 10mg/vial', 'MOTS-c Mitochondrial-Derived Peptide 10mg/vial. 1 flaconcino.', 'hgh-peptidi', 5000, 2700, 100, true, '{"activeName": "MOTS-c Mitochondrial-Derived Peptide 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('peg-mgf', 'Deus Medical', 'PEG MGF', 'Pegylated Mechano Growth Factor 2mg/vial', 'Pegylated Mechano Growth Factor 2mg/vial. 1 flaconcino.', 'hgh-peptidi', 3300, 1600, 100, true, '{"activeName": "Pegylated Mechano Growth Factor 2mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('pnc-27', 'Deus Medical', 'PNC-27', 'PNC-27 Anti-cancer Peptide 5mg/vial', 'PNC-27 Anti-cancer Peptide 5mg/vial. 1 flaconcino.', 'hgh-peptidi', 5000, 3200, 100, true, '{"activeName": "PNC-27 Anti-cancer Peptide 5mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('pt-141', 'Deus Medical', 'PT-141', 'Bremelanotide (PT-141) 10mg/vial', 'Bremelanotide (PT-141) 10mg/vial. 1 flaconcino.', 'sex-support', 3000, 1600, 100, true, '{"activeName": "Bremelanotide (PT-141) 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('retatrutide', 'Deus Medical', 'RETATRUTIDE', 'Retatrutide (GIP/GLP-1/Glucagon) 10mg/vial', 'Retatrutide (GIP/GLP-1/Glucagon) 10mg/vial. 1 flaconcino.', 'brucia-grassi', 9000, 4700, 100, true, '{"activeName": "Retatrutide (GIP/GLP-1/Glucagon) 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('selank', 'Deus Medical', 'SELANK', 'Selank Anxiolytic Peptide 5mg/vial', 'Selank Anxiolytic Peptide 5mg/vial. 1 flaconcino.', 'hgh-peptidi', 1500, 900, 100, true, '{"activeName": "Selank Anxiolytic Peptide 5mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('semaglutide', 'Deus Medical', 'SEMAGLUTIDE', 'Semaglutide (GLP-1) 5mg/vial', 'Semaglutide (GLP-1) 5mg/vial. 1 flaconcino.', 'brucia-grassi', 7000, 3200, 100, true, '{"activeName": "Semaglutide (GLP-1) 5mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('semax', 'Deus Medical', 'SEMAX', 'Semax Heptapeptide 5mg/vial', 'Semax Heptapeptide 5mg/vial. 1 flaconcino.', 'hgh-peptidi', 1500, 900, 100, true, '{"activeName": "Semax Heptapeptide 5mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('tb-500', 'Deus Medical', 'TB 500', 'Thymosin Beta-4 (TB-500) 2mg/vial', 'Thymosin Beta-4 (TB-500) 2mg/vial. 1 flaconcino.', 'hgh-peptidi', 3000, 1500, 100, true, '{"activeName": "Thymosin Beta-4 (TB-500) 2mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('tirzepatide', 'Deus Medical', 'TIRZEPATIDE', 'Tirzepatide (GIP/GLP-1) 10mg/vial', 'Tirzepatide (GIP/GLP-1) 10mg/vial. 1 flaconcino.', 'brucia-grassi', 8000, 4200, 100, true, '{"activeName": "Tirzepatide (GIP/GLP-1) 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('thymalin', 'Deus Medical', 'THYMALIN', 'Thymalin Thymic factor 10mg/vial', 'Thymalin Thymic factor 10mg/vial. 1 flaconcino.', 'hgh-peptidi', 2500, 1300, 100, true, '{"activeName": "Thymalin Thymic factor 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('thymosin-a1', 'Deus Medical', 'THYMOSIN A1', 'Thymosin Alpha-1 10mg/vial', 'Thymosin Alpha-1 10mg/vial. 1 flaconcino.', 'hgh-peptidi', 6000, 3700, 100, true, '{"activeName": "Thymosin Alpha-1 10mg/vial", "packaging": "1 flaconcino"}'::jsonb),
  ('viamed-100', 'Deus Medical', 'VIAMED 100', 'Sildenafil 100mg', 'Sildenafil 100mg. 7 bustine / 100 mg — uso orale.', 'sex-support', 1700, 800, 100, true, '{"activeName": "Sildenafil 100mg", "packaging": "7 bustine / 100 mg — uso orale"}'::jsonb)
on conflict (slug) do update set
  brand = excluded.brand, title = excluded.title, short_description = excluded.short_description,
  description = excluded.description, category = excluded.category, price_cents = excluded.price_cents,
  cost_cents = excluded.cost_cents, specs = excluded.specs, updated_at = now();
